language: java
jdk:
  -openjdk11

branches:
  only:
    - timo

before_deploy:
  - zip -r dnd-5th-4-backend *
  - mkdir -p deploy
  - mv dnd-5th-4-backend.zip deploy/dnd-5th-4-backend.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: dnd-5th-4-backend-deploy
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: timointhebush/dnd-5th-4-backend
      branch: timo

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - junzzang97@naver.com