jasypt:
  encryptor:
    bean: encryptorBean

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://dnd-4-db.ccjxwmigqcii.ap-northeast-2.rds.amazonaws.com:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 0904zxcv?
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug